/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb778',
        'primary-container': '#3f51b5',
        'on-secondary': '#ffffff',
        'surface-dim': '#dadadc',
        'on-tertiary-fixed': '#2e1500',
        'on-error-container': '#93000a',
        secondary: '#006b5c',
        'surface-bright': '#f9f9fc',
        'surface-container-high': '#e8e8ea',
        'secondary-container': '#68fadd',
        'on-primary-container': '#cacfff',
        background: '#f9f9fc',
        'surface-container': '#eeeef0',
        'surface-container-highest': '#e2e2e5',
        'on-secondary-container': '#007261',
        'outline-variant': '#c5c5d4',
        'secondary-fixed-dim': '#44ddc1',
        tertiary: '#663700',
        surface: '#f9f9fc',
        'primary-fixed-dim': '#bac3ff',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#293ca0',
        'surface-variant': '#e2e2e5',
        outline: '#757684',
        error: '#ba1a1a',
        'secondary-fixed': '#68fadd',
        'on-surface': '#1a1c1e',
        'on-background': '#1a1c1e',
        'on-tertiary-fixed-variant': '#6c3a00',
        'tertiary-fixed': '#ffdcc1',
        'on-surface-variant': '#454652',
        'inverse-on-surface': '#f0f0f3',
        'primary-fixed': '#dee0ff',
        'inverse-primary': '#bac3ff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#00105c',
        'on-tertiary-container': '#ffc798',
        'inverse-surface': '#2f3133',
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        primary: '#24389c',
        'surface-tint': '#4355b9',
        'surface-container-low': '#f3f3f6',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#00201a',
        'tertiary-container': '#884b00',
        'on-secondary-fixed-variant': '#005145',
        'on-secondary-fixed-dim': '#44ddc1',
        'secondary-fixed-container': '#00382f',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        xl: '40px',
        xs: '4px',
        md: '16px',
        gutter: '24px',
        sm: '8px',
        base: '4px',
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'title-md': ['Inter'],
        'body-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'headline-xl': ['Inter'],
        'label-caps': ['JetBrains Mono'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-xl': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-caps': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': [
          '24px',
          { lineHeight: '32px', fontWeight: '700' },
        ],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(36, 56, 156, 0.4)' },
          '50%': { boxShadow: '0 0 0 8px rgba(36, 56, 156, 0)' },
        },
        'heart-beat': {
          '0%': { transform: 'scale(1)' },
          '25%': { transform: 'scale(1.3)' },
          '50%': { transform: 'scale(1)' },
          '75%': { transform: 'scale(1.3)' },
          '100%': { transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-up': 'slide-up 0.4s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-out-right': 'slide-out-right 0.3s ease-out',
        'scale-in': 'scale-in 0.2s ease-out',
        'pulse-glow': 'pulse-glow 2s infinite',
        'heart-beat': 'heart-beat 0.6s ease-in-out',
        shimmer: 'shimmer 2s linear infinite',
      },
    },
  },
  plugins: [],
};
